version: '3.6'
services:
  app:
    build:
      context: .
      target: development
    environment:
      - ENV=/home/node/shell/ash.sh
      - PROJECT=__PROJECT_NAME__
    tty: true
    volumes:
      - ../node-in-a-box-shell/source:/home/node/shell
      - ./config:/home/node/config
      - ./source:/home/node/app/source
    working_dir: /home/node/app
